apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres-service
    name: postgres-service-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-app
    name: postgres-app-db
    
  