apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-app
    name: postgres-app-db
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"