apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-service
    name: redis-service-db
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
      app: redis-pod
      name: redis-app-db
    
  