apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
    name: resilt-service-fe
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: result-app
    name: result-app-fe
